/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Poker",
  primary: "#EF4444",
  secondary: "#991B1B",
  splash: {
    glow: "rgba(153,27,27,0.6)",
    sallyGlow: "rgba(239,68,68,0.8)",
    pillBorder: "rgba(239,68,68,0.5)",
    pillBg: "rgba(153,27,27,0.15)",
    pillText: "#FECACA",
    suit: "♠",
    suit2: "♥",
  },
  slides: {
    slide2: { tint: ["rgba(239,68,68,0.55)","rgba(153,27,27,0.7)","rgba(40,8,8,0.95)"], variant: "scattered" },
    slide3: { tint: ["rgba(220,38,38,0.45)","rgba(127,29,29,0.85)","rgba(40,8,8,0.95)"], variant: "spread" },
    slide4: { tint: ["rgba(245,158,11,0.45)","rgba(239,68,68,0.7)","rgba(40,8,8,0.95)"], variant: "fan" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
